project:
  type: website

website:
  title: "VNIR Spectroscopic Sensing of Plastic Waste"
  navbar:
    left:
      - href: index.qmd
        text: Home
  
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



